name: Create Extension Release

on:
  push:
    tags:
      - 'v*' # Runs only when a tag matching 'v*' (e.g., v1.0.0) is pushed.

jobs:
  release:
    name: Build and Release Extension
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and Bun
      - name: Set up Node.js and Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Build and Zip the extension
      - name: Build and Zip
        run: |
          bun run package

      # Step 5: Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🚀 New release of the Email Default Reply extension!
            - Automatic build and packaging
          files: ./extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: TODO: Publish the extension to the Chrome Web Store
